In [1]:
import numpy as np

In [5]:
H_12 = np.array([[2.,-2.], [-2.,2.]])
H_11 = np.zeros((2,2),dtype =np.float)
H_11[0,0] = 200
H_12, H_11

(array([[ 2., -2.],
        [-2.,  2.]]), array([[200.,   0.],
        [  0.,   0.]]))

In [6]:
b = np.array([[2.], [-2.]])
b

array([[ 2.],
       [-2.]])

In [7]:
-1 * np.matmul(np.linalg.inv(H_12+ H_11),b)

array([[-0.],
       [ 1.]])